apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: workers-python
spec:
  type: LoadBalancer
  ports:
  - port: 6000
    targetPort: 5000
    protocol: TCP
  selector:
    app: workers-python
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: workers-python
  replicas: 4
  template:
    metadata:
      labels:
        app: workers-python
    spec:
      containers:
      - name: workers-python
        image: danira/flask:latest
        env:
          - name: ip
            value: "worker-backend-service"
          - name: port
            value: "80"
        ports:
        - containerPort: 5000