apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-flask-app
  template:
    metadata:
      labels:
        app: simple-flask-app
    spec:
      containers:
        - name: simple-flask-app
          image: danira/lol
          env:
            - name: ip
              value: "worker-backend-service"
            - name: port
              value: "81"
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: simple-flask-app
spec:
  selector:
    app: simple-flask-app
  ports:
    - port: 80
      name: worker-front-service-port
      protocol: TCP
      targetPort: 8083
  type: LoadBalancer