apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: workers-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers-python
spec:
  selector:
    matchLabels:
      app: workers-python
  replicas: 4
  template:
    metadata:
      labels:
        app: workers-python
    spec:
      containers:
      - name: workers-python
        image: python:latest
        ports:
        - containerPort: 5000