version: "3.8"
services:
  web:
    build: .
    depends_on: 
      - db
    ports: 
      - "80:8080"
    environment:
      - MYSQL_HOST:localhost=db
      - MYSQL_HOST:port=3306
    command: sh -c "/wait && /sayhello"

  db:
    build: ./DB



