apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-back-end-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: workerBackendService
  template:
    metadata:
      labels:
        app: workerBackendService
    spec:
      containers:
        - name: worker-backend
          image: ddenis1994/worker_backend
          env:
            - name: MYSQL_HOST-localhost
              value: "worker-db-service"
            - name: MYSQL_HOST-port
              value: "3306"
          ports:
            - containerPort: 8080
              name: worker-backend
          imagePullPolicy: Always


---
apiVersion: v1
kind: Service
metadata:
  name: worker-backend-service
spec:
  selector:
    app: workerBackendService
  ports:
    - port: 81
      name: worker-backend-service-port
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer